version: '3'
services:

  # BACKING SERVICES ============================

  # RabbitMQ
  rabbit:
    image: rabbitmq:3-management
    env_file:
      - env/rabbit.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sdx2

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - sdx2

  # APPLICATION SERVICES ========================

  gateway:
    build: ./cmd/sdx-survey-gateway-service
    ports:
      - "8001:5000"
    depends_on:
      - "rabbit"
      - "store"
    env_file:
      - env/rabbit.env
    environment:
      - "PORT=5000"
      - "STORE_URL=http://store:5000"
    networks:
      - "sdx2"
  
  store:
    build: ./cmd/sdx-store-service
    networks: 
      - "sdx2"
    ports:
      - "8002:5000"
    environment:
      - "PORT=5000"
  
  legacy_router:
    build: ./cmd/sdx-legacy-router-service
    networks:
      - "sdx2"
    ports:
      - "8003:5000"
    depends_on:
      - "redis"
    env_file:
      - env/rabbit.env
    environment:
      - "PORT=5000"

  receipt_sink:
    build: ./cmd/receipt-sink-service
    networks: 
      - "sdx2"
    ports:
      - "8004:5000"
    depends_on:
      - "rabbit"
      - "gateway"
    env_file:
      - env/rabbit.env
    environment:
      - "PORT=5000"

  # ---- Downstream ----

  commonsoftware:
    build: ./cmd/sdx-commonsoftware-service
    networks:
      - "sdx2"
    ports:
      - "8005:5000"
    depends_on:
      - "rabbit"
      - "legacy_router"
    env_file:
      - env/rabbit.env
    environment:
      - "PORT=5000"

# NETWORKS ======================================

networks:
  sdx2:
    driver: bridge