version: '3'
services:

  # NB. This compose can be used to spin up gateway in isolation - it won't
  #     do much without the other services but can be used to test basic
  #     functionality and stop signals etc.

  # BACKING SERVICES ============================

  # RabbitMQ
  rabbit:
    image: rabbitmq:3-management
    env_file:
      - ../env/rabbit.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sdx2

  # APPLICATION SERVICES ========================

  gateway:
    build: .
    ports:
      - "8001:5000"
    depends_on:
      - "rabbit"
    env_file:
      - ../env/rabbit.env
    environment:
      - "PORT=5000"
      - "STORE_URL=http://store:5000"
    networks:
      - "sdx2"

# NETWORKS ======================================

networks:
  sdx2:
    driver: bridge